---
title: "Heat Map Explorations"
author: "Jacob Peoples"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("common.R")
uni <- load_unimodal()
multi <- load_multimodal()
```

# Unimodal Visualizations

```{r initial heatmap, fig.width=6, fig.height=4, echo=FALSE}
library(patchwork)
p1 <- ggplot(uni, aes(y=Model_Type, x=1, fill=pmax(Test_Median, 0.5))) + 
  my_heat_map + 
  facet_grid(rows=vars(Surv_Type), cols=vars(feature_spec), switch='y') +
  labs(x = "Feature Type", y = "Model Type", fill = "C-index") +
  scale_y_discrete(position='right') + 
  scale_x_continuous(position='top') +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.title.x=element_blank(),
        axis.line.y = element_blank(),
        panel.spacing = unit(0, 'lines'),
        axis.text.y=element_blank(), axis.title.y=element_blank(), axis.ticks.y = element_blank(), 
        plot.margin = margin(r=0, unit="mm"))

p2 <- uni %>% 
  group_by(Model_Type, Surv_Type) %>% 
  summarize(Model_Type = first(Model_Type), Surv_Type=first(Surv_Type)) %>% 
  ggplot(aes(x=1, y=Model_Type)) + 
  geom_tile(aes(x=1), fill='white', color='black', lwd=0.6) +
  geom_text(aes(x=1, label=Model_Type)) +
  theme_minimal() + 
  facet_grid(rows=vars(Surv_Type)) +
  theme(
    axis.line = element_blank(), 
    axis.ticks = element_blank(), 
    axis.text = element_blank(), 
    axis.title.y = element_blank(),
    panel.grid = element_blank(), 
    strip.text = element_blank(), 
    panel.spacing.x = unit(0, "mm"),
    plot.margin=margin(0, 0,0,0, unit="mm"), 
    #axis.line.x = element_line()
    ) +
  scale_x_continuous(position="top", limits=c(0.5,1.5)) +
  labs(x = "Model Type")
  #ggtitle("Model Type")

p <- p1 + p2 + plot_layout(widths=c(4, 1), guides='collect')
ggsave("uni_heatmap.svg", p)
p
```

# Multi-modal visualizations

```{r uninitial heat map, fig.width=8, fig.height=8, echo=FALSE}
p1 <- ggplot(multi, aes(x=Late_Model_Type, y=Joint_Model_Type, fill=pmax(Test_Median,0.5))) + 
  my_tiny_heat_map + 
  facet_grid(cols=vars(Imaging_Feature_Type), rows=vars(Surv_Type), switch='y') +
  labs(x = "Late Fusion Model", y = "Image Model Type", fill = "C-index") +
  scale_y_discrete(position='right') + 
  theme(
        panel.spacing = unit(0, 'lines'),
        axis.text.y=element_blank(), axis.title.y=element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank(),
        plot.margin = margin(r=0, unit='mm'))

p2 <- multi %>%
  pivot_longer(cols=c("Imaging_Model_Type", "Clinical_Model_Type")) %>%
  mutate(name=plyr::revalue(factor(name, levels=c("Imaging_Model_Type", "Clinical_Model_Type")),
                            c("Imaging_Model_Type"="Imaging", "Clinical_Model_Type"="Clinical"))) %>%
  group_by(Surv_Type, Joint_Model_Type, name, value) %>%
  summarize(n=n()) %>% #, Joint_Model_Type = first(Joint_Model_Type), name=first(name), value=first(value)) %>%
  ggplot(aes(x=name, y=Joint_Model_Type)) +
  geom_tile(fill='white', color='black', lwd=0.6) +
  geom_text(aes(label=value)) +
  theme_classic() + 
  facet_grid(rows=vars(Surv_Type), switch='y') +
  theme(
    axis.line = element_blank(), 
    axis.ticks = element_blank(), 
    axis.text.y = element_blank(), 
    axis.title.y = element_blank(),
    panel.grid = element_blank(), 
    strip.background = element_blank(),
    strip.text = element_blank(),
    panel.spacing = unit(0, "mm"),
    plot.margin=margin(0, 0,0,0, "mm"), 
    #axis.line.x.bottom = element_line()
    ) +
  scale_x_discrete(position="top") +
  labs(x = "Model Type")

p <- p1 + p2 + plot_layout(widths=c(4,2), guides='collect')
ggsave("multi_heatmap.svg", p)
p
```
